name: month_picker_dialog_2_example
description: Demonstrates how to use the month_picker_dialog_2 plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  month_picker_dialog_2:
    path: ../

flutter:
  uses-material-design: true