name: month_picker_dialog_2
description: Internationalized dialog for picking a single month from an infinite list of years.
version: 0.5.5
homepage: https://github.com/Macacoazul01/month_picker_dialog_2

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.27.5
  intl: ^0.17.0

flutter:
