name: month_picker_dialog
description: Internationalized dialog for picking a single month from an infinite list of years.
version: 0.4.1
homepage: https://github.com/hmkrivoj/month_picker_dialog

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.27.4

flutter:
